version: '3.3'
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: memo
        container_name: memo-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - memo

    db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'memo'
          MYSQL_USER: 'memo'
          MYSQL_PASSWORD: '123456789'
          MYSQL_ROOT_PASSWORD: '123456789'
        ports:
          - '3306:3306'
        expose:
          - '3306'
        networks:
            - memo

    nginx:
      image: nginx:1.17-alpine
      container_name: memo-nginx
      restart: unless-stopped
      ports:
          - 8000:80
      volumes:
          - ./:/var/www
          - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
          - memo

networks:
    memo:
        driver: bridge
